// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/alphagov/paas-s3-broker/s3"
)

type FakeClient struct {
	CreateBucketStub        func(name string) error
	createBucketMutex       sync.RWMutex
	createBucketArgsForCall []struct {
		name string
	}
	createBucketReturns struct {
		result1 error
	}
	createBucketReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteBucketStub        func(name string) error
	deleteBucketMutex       sync.RWMutex
	deleteBucketArgsForCall []struct {
		name string
	}
	deleteBucketReturns struct {
		result1 error
	}
	deleteBucketReturnsOnCall map[int]struct {
		result1 error
	}
	AddUserToBucketStub        func(username, bucketName string) (s3.BucketCredentials, error)
	addUserToBucketMutex       sync.RWMutex
	addUserToBucketArgsForCall []struct {
		username   string
		bucketName string
	}
	addUserToBucketReturns struct {
		result1 s3.BucketCredentials
		result2 error
	}
	addUserToBucketReturnsOnCall map[int]struct {
		result1 s3.BucketCredentials
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) CreateBucket(name string) error {
	fake.createBucketMutex.Lock()
	ret, specificReturn := fake.createBucketReturnsOnCall[len(fake.createBucketArgsForCall)]
	fake.createBucketArgsForCall = append(fake.createBucketArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("CreateBucket", []interface{}{name})
	fake.createBucketMutex.Unlock()
	if fake.CreateBucketStub != nil {
		return fake.CreateBucketStub(name)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.createBucketReturns.result1
}

func (fake *FakeClient) CreateBucketCallCount() int {
	fake.createBucketMutex.RLock()
	defer fake.createBucketMutex.RUnlock()
	return len(fake.createBucketArgsForCall)
}

func (fake *FakeClient) CreateBucketArgsForCall(i int) string {
	fake.createBucketMutex.RLock()
	defer fake.createBucketMutex.RUnlock()
	return fake.createBucketArgsForCall[i].name
}

func (fake *FakeClient) CreateBucketReturns(result1 error) {
	fake.CreateBucketStub = nil
	fake.createBucketReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CreateBucketReturnsOnCall(i int, result1 error) {
	fake.CreateBucketStub = nil
	if fake.createBucketReturnsOnCall == nil {
		fake.createBucketReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createBucketReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteBucket(name string) error {
	fake.deleteBucketMutex.Lock()
	ret, specificReturn := fake.deleteBucketReturnsOnCall[len(fake.deleteBucketArgsForCall)]
	fake.deleteBucketArgsForCall = append(fake.deleteBucketArgsForCall, struct {
		name string
	}{name})
	fake.recordInvocation("DeleteBucket", []interface{}{name})
	fake.deleteBucketMutex.Unlock()
	if fake.DeleteBucketStub != nil {
		return fake.DeleteBucketStub(name)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteBucketReturns.result1
}

func (fake *FakeClient) DeleteBucketCallCount() int {
	fake.deleteBucketMutex.RLock()
	defer fake.deleteBucketMutex.RUnlock()
	return len(fake.deleteBucketArgsForCall)
}

func (fake *FakeClient) DeleteBucketArgsForCall(i int) string {
	fake.deleteBucketMutex.RLock()
	defer fake.deleteBucketMutex.RUnlock()
	return fake.deleteBucketArgsForCall[i].name
}

func (fake *FakeClient) DeleteBucketReturns(result1 error) {
	fake.DeleteBucketStub = nil
	fake.deleteBucketReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteBucketReturnsOnCall(i int, result1 error) {
	fake.DeleteBucketStub = nil
	if fake.deleteBucketReturnsOnCall == nil {
		fake.deleteBucketReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteBucketReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) AddUserToBucket(username string, bucketName string) (s3.BucketCredentials, error) {
	fake.addUserToBucketMutex.Lock()
	ret, specificReturn := fake.addUserToBucketReturnsOnCall[len(fake.addUserToBucketArgsForCall)]
	fake.addUserToBucketArgsForCall = append(fake.addUserToBucketArgsForCall, struct {
		username   string
		bucketName string
	}{username, bucketName})
	fake.recordInvocation("AddUserToBucket", []interface{}{username, bucketName})
	fake.addUserToBucketMutex.Unlock()
	if fake.AddUserToBucketStub != nil {
		return fake.AddUserToBucketStub(username, bucketName)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.addUserToBucketReturns.result1, fake.addUserToBucketReturns.result2
}

func (fake *FakeClient) AddUserToBucketCallCount() int {
	fake.addUserToBucketMutex.RLock()
	defer fake.addUserToBucketMutex.RUnlock()
	return len(fake.addUserToBucketArgsForCall)
}

func (fake *FakeClient) AddUserToBucketArgsForCall(i int) (string, string) {
	fake.addUserToBucketMutex.RLock()
	defer fake.addUserToBucketMutex.RUnlock()
	return fake.addUserToBucketArgsForCall[i].username, fake.addUserToBucketArgsForCall[i].bucketName
}

func (fake *FakeClient) AddUserToBucketReturns(result1 s3.BucketCredentials, result2 error) {
	fake.AddUserToBucketStub = nil
	fake.addUserToBucketReturns = struct {
		result1 s3.BucketCredentials
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) AddUserToBucketReturnsOnCall(i int, result1 s3.BucketCredentials, result2 error) {
	fake.AddUserToBucketStub = nil
	if fake.addUserToBucketReturnsOnCall == nil {
		fake.addUserToBucketReturnsOnCall = make(map[int]struct {
			result1 s3.BucketCredentials
			result2 error
		})
	}
	fake.addUserToBucketReturnsOnCall[i] = struct {
		result1 s3.BucketCredentials
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createBucketMutex.RLock()
	defer fake.createBucketMutex.RUnlock()
	fake.deleteBucketMutex.RLock()
	defer fake.deleteBucketMutex.RUnlock()
	fake.addUserToBucketMutex.RLock()
	defer fake.addUserToBucketMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ s3.Client = new(FakeClient)
